server.port=8080

spring.datasource.url=jdbc:mariadb://db-easycrud.c9o0wcyo6tld.ap-south-1.rds.amazonaws.com:3306/studentapp-db
spring.datasource.username=yash
spring.datasource.password=yashpatel

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true